version: 2.1

executors:
  rust-stable:
    docker:
      - image: circleci/rust:latest
    working_directory: /home/circleci/build
  rust-nightly:
    docker:
      - image: rustlang/rust:nightly
    working_directory: /home/build

jobs:
  cargo_fetch:
    executor: rust-stable
    steps:
      - checkout
      - run:
          name: Get top commit hash of cargo registry index
          command: |
            git ls-remote --heads https://github.com/rust-lang/crates.io-index.git master |
              cut -f 1 | tee .circleci/crates.io-index.head
      - restore_cache:
          name: Restore cargo registry index from cache
          keys:
            - cargo-index-v1-{{ checksum ".circleci/crates.io-index.head" }}
            - cargo-index-v1-
      - run:
          name: Generate Cargo.lock and update cargo registry index
          command: |
            cargo generate-lockfile
            git -C /usr/local/cargo/registry/index/github.com-1ecc6299db9ec823 \
                show-ref -s refs/remotes/origin/master |
              tee .circleci/crates.io-index.head
      - save_cache:
          name: Save cargo registry index into cache
          key: cargo-index-v1-{{ checksum ".circleci/crates.io-index.head" }}
          paths:
            - /usr/local/cargo/registry/index
      - restore_cache:
          name: Restore dependency crates from cache
          keys:
            - cargo-deps-v1-{{ checksum "Cargo.lock" }}
            - cargo-deps-v1-
      - run: cargo fetch
      - save_cache:
          name: Save dependency crates into cache
          key: cargo-deps-v1-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry/cache
      - persist_to_workspace:
          root: .
          paths:
            - Cargo.lock
            - .circleci/crates.io-index.head

  test_debug:
    executor: rust-stable
    steps:
      - test:
          mode: --all-targets

  test_release:
    executor: rust-stable
    steps:
      - test:
          mode: --release --all-targets

  test_no_default_features:
    executor: rust-stable
    environment:
      RUSTFLAGS: -D warnings
    steps:
      - test:
          mode: --manifest-path chain-network/Cargo.toml --no-default-features

commands:
  test:
    description: "Steps for the test jobs"
    parameters:
      mode:
        type: string
        default: ''
      cargo_behavior:
        type: string
        default: --locked --verbose
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          name: Restore cargo registry index from cache
          keys:
            - cargo-index-v1-{{ checksum ".circleci/crates.io-index.head" }}
      - restore_cache:
          name: Restore dependency crates from cache
          keys:
            - cargo-deps-v1-{{ checksum "Cargo.lock" }}
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build with << parameters.mode >>
          command: |
            cargo build << parameters.mode >> << parameters.cargo_behavior >>
      - run:
          name: Test with << parameters.mode >>
          environment:
            RUST_BACKTRACE: 1
          command: |
            cargo test << parameters.mode >> << parameters.cargo_behavior >>

workflows:
  version: 2
  test_all:
    jobs:
      - cargo_fetch
      - test_debug:
          requires:
            - cargo_fetch
      - test_release:
          requires:
            - cargo_fetch
      - test_no_default_features:
          requires:
            - cargo_fetch
